version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"  # Acceso desde el navegador
    volumes:
      - ./src:/var/www/html  # Código fuente PHP montado
    depends_on:
      - db  # Asegura que el contenedor db esté listo antes de levantar PHP

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Puerto para conexiones MySQL desde el host

volumes:
  db_data:
