version: '3.8'

services:
  php-apache:
    build: .
    container_name: php-apache
    ports:
      - "8080:80"  # Puerto público para acceso desde el navegador
    volumes:
      - ./src:/var/www/html  # Montar el código fuente PHP en el contenedor
    depends_on:
      - db  # Asegura que el contenedor de MySQL esté listo antes de Apache

  db:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: user_password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"  # Puerto público para acceso a MySQL

volumes:
  db_data:
